import Head from "next/head";
import localFont from "next/font/local";
import type { AppProps } from "next/app";
import "@/styles/globals.css";
import styles from "@/styles/App.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Jason Melgoza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <h1>Jason Melgoza</h1>
        </header>
        <Component {...pageProps} />
        <footer>
          <p>&copy; Jason Melgoza</p>
        </footer>
      </main>
    </>
  );
}
